import algosdk from "algosdk";
import { VERSION } from "../globals";

// Versioning
let reserveAddress;
let treasuryAddress;
if (VERSION == "MAINNET") {
  reserveAddress = "J2E2XXS4FTW3POVNZIHRIHTFRGOWEWX65NFYIVYIA27HUK63NWT65OLB2Y";
  treasuryAddress =
    "MTMJ5ADRK3CFG3HGUI7FS4Y55WGCUO5CRUMVNBZ7FW5IIG6T3IU2VJHUMM";
} else if (VERSION == "TESTNET1") {
  reserveAddress = "UEF5SCP5UENRG2LROI5APWDEQDIRF76DCBGL732RUGKUFQPDCEYO44RW7E";
  treasuryAddress =
    "5FVZFQPWBMMUX7XQZ3IQYWSOJF6MTGB7J2O5GN7SG3IXQJ3LXEPC2NQAKQ";
}

function contractStringToBytes(string) {
  return Uint8Array.from(atob(string), (c) => c.charCodeAt(0));
}

// Setup
const encoder = new TextEncoder();

// Last updated: 23.02.2022
let _reserveString =
  "BSAIAKmPkSMEBwEIgAG4j5EjJgIHUHJvZ3JhbagEBSAJALiPkSMDAgEEqY+RIwUGJgIgvunrGbzJ+Z+dLIbzhDzEhJKtXhb0bw31HISV2mcN2mIg6WuSwfYLGUv+8M7RDFpOSXzJmD9OndM38jbReCdruR4tFyISQAFdLRchBBJAAS0tFyUSQADiLRckEkAAoS0XIQUSQACBLRchBxJAAEotFyEIEkAAAQAxGCMSMRkiEhA2GgCAB0F1Y3Rpb24SEDIEJBIzABgjEhAzABkiEhA3ABoAgAhDbGVhckFwcBIQMwEZJBIQEUIBWjIEJBIzABkiEhAzABgjEhA3ABoAgAhNb3JlR0FSRBIQMwEAKBIQMwEHKRIQQgErMRkhBBIxGCMSEDEgMgMSEDEBIhIQQgETMgQhBRIzABkiEhAzABgjEhA3ABoAgApDbG9zZU5vRmVlEhA3ADAAIQYSEDMBACgSEDMCGSQSEEIA2TIEIQUSMwAZIhIQMwAYIxIQNwAaAIAIQ2xvc2VGZWUSEDcAMAAhBhIQMwEAKBIQMwIZJBIQMwMHKRIQMwMJKBIQQgCVMgQhBxIzABklEhAzABgjEhA3ADAAIQYSEDMDFCkSEDMEFCgSEEIAbTMACIF0EjMAACgSEDMBIDIDEhAzAQEiEhAyBCUSQAAxMgQkEjMBECEIEhAzARgjExAzAhgjEhAzAhkiEhA3AhoAgAhBcHBDaGVjaxIQEEIAHDMBECEEEjMBCCISEDMBCTIDEhAzARAlEhFC/+BDLRciEkABIS0XIQQSQABPLReBAhJAAAEAMgSBAxIzABkiEhAzABghBxIQNwAaAIAITW9yZUdBUkQSEDcAMAAjEhAzAhAkEhAzAgEiEhAzAhUyAxIQMwIgMgMSEEIA6TIEJBIzABkiEhAzABghBxIQNwAaAIALTmV3UG9zaXRpb24SEDcAHAEzAQcSEDcAMAAjEhAzARAhBBIQMwEAMwAAEhAzAQcoKVAigRxSMwAAUCgpUIE8gcUDUlA3ADABiACIUCgpUIHGA4GvBFJQAxIQMwIQIQQSEDMCADMBABIQMwIHgCDpa5LB9gsZS/7wztEMWk5JfMmYP06d0zfyNtF4J2u5HhIQMwMQJBIQMwMRIxIQMwMBIhIQMwMVMgMSEDMDIDIDEhBCAB8xECQSMREjEhAxEiISEDEgMgMSEDEVMgMSEDEBIhIQQzUANAAWJSEFUjUBNAAhBg9BADM0ACEGCjUCNAIhBg9AAA80ATQCFiUhBVJQNQFCABU0ATQCFiUhBVJQNQE0AiWRNQJC/9Q0AYk=";
if (VERSION == "MAINNET") {
  _reserveString =
    "BiAGAITcu8YCBAGAAaPdu8YCJgIHUHJvZ3JhbaoEBiAJAKPdu8YCAwIBBITcu8YCBQYmAiC+6esZvMn5n50shvOEPMSEkq1eFvRvDfUchJXaZw3aYiBk2J6AcVbEU2zmoj5Zcx3tjCo7oo0ZVoc/LbqEG9PaKS0XIhJAAV0tFyEEEkABLS0XJRJAAOItFyQSQAChLRchBRJAAIEtFyEHEkAASi0XIQgSQAABADEYIxIxGSISEDYaAIAHQXVjdGlvbhIQMgQkEjMAGCMSEDMAGSISEDcAGgCACENsZWFyQXBwEhAzARkkEhARQgFaMgQkEjMAGSISEDMAGCMSEDcAGgCACE1vcmVHQVJEEhAzAQAoEhAzAQcpEhBCASsxGSEEEjEYIxIQMSAyAxIQMQEiEhBCARMyBCEFEjMAGSISEDMAGCMSEDcAGgCACkNsb3NlTm9GZWUSEDcAMAAhBhIQMwEAKBIQMwIZJBIQQgDZMgQhBRIzABkiEhAzABgjEhA3ABoAgAhDbG9zZUZlZRIQNwAwACEGEhAzAQAoEhAzAhkkEhAzAwcpEhAzAwkoEhBCAJUyBCEHEjMAGSUSEDMAGCMSEDcAMAAhBhIQMwMUKRIQMwQUKBIQQgBtMwAIgXQSMwAAKBIQMwEgMgMSEDMBASISEDIEJRJAADEyBCQSMwEQIQgSEDMBGCMTEDMCGCMSEDMCGSISEDcCGgCACEFwcENoZWNrEhAQQgAcMwEQIQQSMwEIIhIQMwEJMgMSEDMBECUSEUL/4EMtFyISQAEcLRclEkAATy0XgQISQAABADIEgQMSMwAZIhIQMwAYIQUSEDcAGgCACE1vcmVHQVJEEhA3ADAAIxIQMwIQJBIQMwIBIhIQMwIVMgMSEDMCIDIDEhBCAOUyBCQSMwAZIhIQMwAYIQUSEDcAGgCAC05ld1Bvc2l0aW9uEhA3ABwBMwEHEhA3ADAAIxIQMwEQJRIQMwEAMwAAEhAzAQcoKVBXAB4zAABQKClQgT6BiQNYUDcAMAGIAIZQKClQgcgDgWlYUAMSEDMCECUSEDMCADMBABIQMwIHgCBk2J6AcVbEU2zmoj5Zcx3tjCo7oo0ZVoc/LbqEG9PaKRIQMwMQJBIQMwMRIxIQMwMBIhIQMwMVMgMSEDMDIDIDEhBCAB8xECQSMREjEhAxEiISEDEgMgMSEDEVMgMSEDEBIhIQQzUANAAWVwcBNQE0ACEED0EAMjQAIQQKNQI0AiEED0AADjQBNAIWVwcBUDUBQgAVNAE0AhZXBwFQNQE0AoEHkTUCQv/VNAGJ";
}
const reserveString = _reserveString;

// Last updated: 22.02.2022
let cdpTemplateString =
  "BSAJALiPkSMDAgEEqY+RIwUGJgIgvunrGbzJ+Z+dLIbzhDzEhJKtXhb0bw31HISV2mcN2mIg6WuSwfYLGUv+8M7RDFpOSXzJmD9OndM38jbReCdruR4tFyISQAFdLRchBBJAAS0tFyUSQADiLRckEkAAoS0XIQUSQACBLRchBxJAAEotFyEIEkAAAQAxGCMSMRkiEhA2GgCAB0F1Y3Rpb24SEDIEJBIzABgjEhAzABkiEhA3ABoAgAhDbGVhckFwcBIQMwEZJBIQEUIBWjIEJBIzABkiEhAzABgjEhA3ABoAgAhNb3JlR0FSRBIQMwEAKBIQMwEHKRIQQgErMRkhBBIxGCMSEDEgMgMSEDEBIhIQQgETMgQhBRIzABkiEhAzABgjEhA3ABoAgApDbG9zZU5vRmVlEhA3ADAAIQYSEDMBACgSEDMCGSQSEEIA2TIEIQUSMwAZIhIQMwAYIxIQNwAaAIAIQ2xvc2VGZWUSEDcAMAAhBhIQMwEAKBIQMwIZJBIQMwMHKRIQMwMJKBIQQgCVMgQhBxIzABklEhAzABgjEhA3ADAAIQYSEDMDFCkSEDMEFCgSEEIAbTMACIF0EjMAACgSEDMBIDIDEhAzAQEiEhAyBCUSQAAxMgQkEjMBECEIEhAzARgjExAzAhgjEhAzAhkiEhA3AhoAgAhBcHBDaGVjaxIQEEIAHDMBECEEEjMBCCISEDMBCTIDEhAzARAlEhFC/+BD";
if (VERSION == "MAINNET") {
  cdpTemplateString =
    "BiAJAKPdu8YCAwIBBITcu8YCBQYmAiCJ292BS9oSZyC9CmaKFG4/FMfHnby4lnt2559mFLHb3yBk2J6AcVbEU2zmoj5Zcx3tjCo7oo0ZVoc/LbqEG9PaKS0XIhJAAV0tFyEEEkABLS0XJRJAAOItFyQSQAChLRchBRJAAIEtFyEHEkAASi0XIQgSQAABADEYIxIxGSISEDYaAIAHQXVjdGlvbhIQMgQkEjMAGCMSEDMAGSISEDcAGgCACENsZWFyQXBwEhAzARkkEhARQgFaMgQkEjMAGSISEDMAGCMSEDcAGgCACE1vcmVHQVJEEhAzAQAoEhAzAQcpEhBCASsxGSEEEjEYIxIQMSAyAxIQMQEiEhBCARMyBCEFEjMAGSISEDMAGCMSEDcAGgCACkNsb3NlTm9GZWUSEDcAMAAhBhIQMwEAKBIQMwIZJBIQQgDZMgQhBRIzABkiEhAzABgjEhA3ABoAgAhDbG9zZUZlZRIQNwAwACEGEhAzAQAoEhAzAhkkEhAzAwcpEhAzAwkoEhBCAJUyBCEHEjMAGSUSEDMAGCMSEDcAMAAhBhIQMwMUKRIQMwQUKBIQQgBtMwAIgQwSMwAAKBIQMwEgMgMSEDMBASISEDIEJRJAADEyBCQSMwEQIQgSEDMBGCMTEDMCGCMSEDMCGSISEDcCGgCACEFwcENoZWNrEhAQQgAcMwEQIQQSMwEIIhIQMwEJMgMSEDMBECUSEUL/4EM=";
}
const cdpTemplate = contractStringToBytes(cdpTemplateString);

// Exports

export const reserve = {
  address: reserveAddress,
  logic: contractStringToBytes(reserveString),
};

let _slices = [0, 21, 53, 446, 447, 552];
if (VERSION == "MAINNET") {
  _slices = [0, 23, 55, 448, 449, 554];
}
const slices = _slices;

export function cdpGen(userAddress, accountID) {
  // XXX: Could cache results once they are done the first time

  let userAddressBytes = algosdk.decodeAddress(userAddress);
  let accountIDBytes = new Uint8Array([accountID]); // XXX: Could add a nice check here that it's a small enough value

  const sub1 = cdpTemplate.slice(slices[0], slices[1]);
  const sub2 = cdpTemplate.slice(slices[2], slices[3]);
  const sub3 = cdpTemplate.slice(slices[4], slices[5]);

  // Crafts the contract with proper insertions
  const contract = new Uint8Array([
    ...sub1,
    ...userAddressBytes.publicKey,
    ...sub2,
    ...accountIDBytes,
    ...sub3,
  ]);

  const account = new algosdk.LogicSigAccount(contract);

  return {
    address: account.address(),
    logic: contract,
  };
}

export const treasury = {
  address: treasuryAddress,
};
